name: Test and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests-and-lints:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
      - name: Execute linter via laravel/pint
        if: always()
        run: ./vendor/bin/pint
      - name: Execute linter via PHPCS
        if: always()
        run: ./vendor/bin/phpcs --standard=PSR12 app/Http/Controllers app/Models database routes/web.php
      - name: Execute linter via PHPStan
        if: always()
        run: ./vendor/bin/phpstan analyse app/Http/Controllers app/Models database routes/web.php tests

  js-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npx eslint resources/
